spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
#    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: true

## logging
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret:
    signatureKey: "youknowProject-secretKey-signatureKey"